---
# sentry/tasks
- yum: name={{item}} state=present
  with_items:
    - python-devel
    - python-psycopg2
    - python-simplejson
    - libxslt-devel
    - libxml2-devel
    - libffi-devel
    - redis
  sudo: yes

- yum: name={{item}} state=present
  with_items:
    - redis
  sudo: yes
  notify: restart redis

- command: chkconfig redis on
  sudo: yes

- name: install virtualenv
  command: /usr/local/bin/pip2.7 install virtualenv creates=/usr/local/bin/virtualenv
  sudo: yes

- name: make app directory
  file: path={{dir_sentry}} state=directory owner=vagrant group=vagrant
  register: result
  sudo: yes

- include: install.yml
  when: result.changed
